---
title: "Solid wood calculations restart"
author: "Sami Hlebak"
date: "Tuesday, November 10, 2015"
output: html_document
---

Here are the parameters:
```{r}
SWDC<-4.54*10^(-7)#from xlsx Parameters&Results $O$17
                  #Derived conversion coefficent
                  #solid wood products carbon factor
                  #average life time
PPHL<-2.53#from xlsx Parameters&Results $P$10
          #Paper products decay rate (half-life)
PPCF<-3.90*10^(-7)#from xlsx Parameters&Results $0$18
                  #Paper products carbon factor
                  #Average lifetime
                  #derived conversion coefficent
VIBY<-0.08#from xlsx swcalc b979
          #tells the values lost when placed in use
          #same for all
IPY<-0.01#percent increase per year from base year
        #from xlsx swcalc b980
        #same for all

```


```{r}
Var1a<-function(y)
  {CalcO(y)*1000}
CalcO<-function(y)
  {calcH(y)+calcL(y)}
calcH<- function(y)
  {swcalcE(y)}
swcalcE<-function(y)
  {swcalcJ*SWDC}
swcalcJ<-function(y)
  {swcalcH-(swcalcH-1)}
swcalcH<-function(y)
  {swcalcW(y)+swcalcC(y)}#find what "offset" does
swcalcW<-function(y)
  {Url*swcalcV(y)}#v is blank
calcL<-function(y)
  {calcJ-(calcJ-1)}
calcJ<-function(y)
  {(exp(-ln(2)/(PPHL)))*(calcD+(calcJ-1)}
calcD<-function(y)
  {controlV(y)*controlAB(y)*PPCF}
controlV<-function(y)
  {controlS(y)+controlT(y)-controlU(y)}
controlS<-function(y)
  #{find stuff in tables}
controlT<-function(y)
  #{find stuff from tables}
controlU<-function(y)
  #{find stuff from tables}
swcalcC<-function(y)
  {swcalc}#each valuse is same year but different thing
```

```{r}

```













