---
title: "SVariable 1A"
author: "Sami Hlebak"
date: "Tuesday, November 10, 2015"
output: html_document
---

Here are the parameters:
```{r}
SWDC<-4.54*10^(-7)#from xlsx Parameters&Results $O$17
                  #Derived conversion coefficent
                  #solid wood products carbon factor
                  #average life time
PPHL<-2.53#from xlsx Parameters&Results $P$10
          #Paper products decay rate (half-life)
PPCF<-3.90*10^(-7)#from xlsx Parameters&Results $0$18
                  #Paper products carbon factor
                  #Average lifetime
                  #derived conversion coefficent
VIBY<-0.08#from xlsx swcalc b979
          #tells the values lost when placed in use
          #same for all
IPY<-0.01#percent increase per year from base year
        #from xlsx swcalc b980
        #same for all

```


```{r}
Var1a<-function(y)
  {CalcO(y)*1000}
  CalcO<-function(y)
    {calcH(y)+calcL(y)}
  calcH<- function(y)
    {swcalcE(y)}
  swcalcE<-function(y)
    {swcalcJ(y)*SWDC}
  swcalcJ<-function(y)
    {swcalcH(y)-swcalc(H-1)}
  swcalcH<-function(y)
    {swcalcW(y)+swcalcC3140(y)}#The years are in the rows here
  swcalcW<-function(y)
    {Url*swcalcV(y)}#v is blank
  swcalcC3140<-function(y)#different c's added,figure out how to code
    {
     swcalcC1139(y)+
     swcalc1293(y)+
     swcalcC1447(y)+
     swcalcC1601(y)+
     swcalcC1755(y)+
     swcalcC1909(y)+
     swcalcC2063(y)+      #for y=1900
     swcalcC2217(y)+
     swcalcC2371(y)+
     swcalcC2525(y)+
     swcalcC2679(y)+
     swcalcC2833(y)+
     swcalcC2987(y)
     } 
#swcalc1138 the year is the row 
#not the column
#swcalcC1138 never changes based on the year
swcalcC1138<-1900 #this is the year that it was placed in use
swcalcC1139<-function(y)
  {swcalcB1139(y)*(exp(-ln(2)/swcalcB920(y)*
  (swcalcC1138-(swcalc1138(y)+1)))*(1-swcalcB982))}
swcalc1293<-function(y)
  {swcalcB1293(y)*(exp(-ln(2)/swcalcC820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcC982))}
swcalcC1447<-function(y)
  {swcalcB1447(y)*(exp(-ln(2)/swcalcD820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcD982))}         
swcalcC1601<-function(y)
  {swcalcB1601(y)*(exp(-ln(2)/swcalcF820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcF982))}
swcalcC1755<-function(y)
  {swcalcB1755(y)*(exp(-ln(2)/swcalcG820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcG982))}
swcalcC1909<-function(y)
  {swcalcB1909(y)*(exp(-ln(2)/swcalcH820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcH982))}
swcalcC2063<-function(y)
  {swcalcB2063(y)*(exp(-ln(2)/swcalcI820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcI982))}
swcalcC2217<-function(y)
  {swcalcB2217(y)*(exp(-ln(2)/swcalcK820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcK982))}
swcalcC2371<-function(y)
  {swcalcB2371(y)*(exp(-ln(2)/swcalcL820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcL982))}
swcalcC2525<-function(y)
  {swcalcB2525(y)*(exp(-ln(2)/swcalcM820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcM982))}
swcalcC2679<-function(y)
  {swcalcB2679(y)*(exp(-ln(2)/swcalcO820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcO982))}
swcalcC2833<-function(y)
  {swcalcB2833(y)*(exp(-ln(2)/swcalcP820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcP982))}
swcalcC2987<-function(y)
  {swcalcB2987(y)*(exp(-ln(2)/swcalcQ820(y)*
  (swcalcC1138(y)-(swcalc1138+1)))*(1-swcalcQ982))}
#____________________________________________________
#starting paper poducts
calcL<-function(y)
  {calcJ(y)-calcJ(y-1)}#fix this 
#maybe use y[n]-y[y-1]
#or diff(y)
calcJ<-function(y)
  {exp(-ln(2)/PPHL*(calcD(y)-calcJ(y-1)))}#fix the y-1
calcD<-function(y)
  {PPCF*controlV(y)*controlAB(y)}
controlV<-function(y)
  {controlS(y)+controlT(y)-controlU(y)}
controlS<-function(y)
  {(Readin table)*1000*(read in table)}
controlT<-function(y)
  {(readin table)*1000*(read in table)}
controlU<-function(y)
  {(readintable*1000*(read in table))}
controlAB<-function(y)
  {((controlAM(y)+controlAN(y)-controlAO(y))-(controlAI(y)+controlAJ(y)-controlAK(y)))/(controlAM(y)+controlAN(y)-controlAO(y))}
controlAM<-function(y)
  {read in table +read in table}
controlAN<-function(y)
  {table+table}
controlAO<-function(y)
  {table+table}
controlAI<-function(y)
  {table}
controlAJ<-function(y)
  {table}
controlAK<-function(y)
  {table}
  
```

```{r}

```













