---
title: "Simulation Bootstrap Regression Lines"
author: "Alan T. Arnholt"
date: "September 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(PASWR2)
plot(totalprice ~ area, data = VIT2005, type = "n")
#
for(i in 1:1000){
  IND <- sample(1:218, 218, replace = TRUE)
  STU <- lm(totalprice~area, data = VIT2005[IND, ])
  abline(coef = coef(STU), col = "pink")
}
abline(lm(totalprice ~ area, data = VIT2005), col = "red")
```

## Using `ggplot` now:

```{r}
library(ggplot2)
g1 <- ggplot(data = VIT2005, aes(x = area, y = totalprice))
#
sims <- 1000
mod <- matrix(NA, sims, 2)
#
for(i in 1:sims){
  IND <- sample(1:218, 218, replace = TRUE)
  mod[i, ] <- coef(lm(totalprice ~ area, data = VIT2005[IND, ]))
}
#
g1 + geom_abline(intercept = mod[, 1], slope = mod[, 2], 
                 color = "pink", size = 0.1) + 
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5, fullrange = TRUE) + 
  theme_bw()
```


```{r}
library(dplyr)
df <- EPIDURALF %>%
  mutate(ease = factor(ease, levels = c("Easy", "Difficult", "Impossible")))
df2 <- df %>%
  group_by(ease, treatment) %>%
  summarise(WT = mean(kg))
df2
```


```{r}
EPIDURALF$ease <- factor(EPIDURALF$ease, levels = c("Easy", "Difficult", "Impossible")) 
DF <- EPIDURALF %>%
  group_by(ease, treatment) %>%
  summarise(WT = round(mean(kg), 4))
DF
DT::datatable(DF)
knitr::kable(xtabs(WT ~ ease + treatment, data = DF), booktabs = TRUE)
```

